name: Liquid City
favicon: null
layout_spectrum: 0.1961686525028199
typography_spectrum: 0.15943543543107808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4655951994936913
  lightness: 0.6573570400942117
  saturation: 0.12393653392791748
  rhythmicContrast: 0.672734115505591
purpose: []
